# docker-compose.yml
services:
  dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    
    volumes:
      # Code source
      - .:/workspace:cached
      
      # Cache uv entre les sessions
      - uv_cache:/root/.cache/uv
      
      # Virtual environment persistant
      - venv:/workspace/.venv
      
      # Config git
      - ~/.gitconfig:/root/.gitconfig:ro
      
    environment:
      - PYTHONPATH=/workspace
      - UV_SYSTEM_PYTHON=1
      
    ports:
      - "8888:8888"  # Jupyter
      - "5001:5000"  # API
    
    working_dir: /workspace
    
    command: >
      bash -c "
        echo '🚀 Starting container...' &&
        bash /workspace/.devcontainer/setup.sh &&
        echo '✅ Ready! Container is running.' &&
        exec bash
      "
    
    stdin_open: true
    tty: true

volumes:
  uv_cache:
  venv: